#+startup:  showeverything indent hidestars
#+title:    My Literate Emacs Configuration
#+options:  H:5 author:t timestamp:t tex:verbatim
#+property: header-args :results silent :exports code

#+toc: headlines 4

* Introduction
#+property: toc
This is my main file for documenting my emacs configuration using the literate programming style.  It uses =org-mode= as a markup language, allowing the =Emacs Lisp= code-blocks to reside in-line with the prose that describes the intention of the code-blocks. When I have prepared the essential configuration, then whenever I save this file, the code-blocks will be tangled into the appropriate =Emacs Lisp= file and the entire =org-mode= file, including the un-evaluated code-blocks, will be exported into the root of the repository as GitHub Flavored Markdown.  

* Files related to this configuration
#+property: toc
As I write this, I am using a variant of Gnu Emacs 30.1, which anticipates the configuration files are stored in the (=user-emacs-directory=), which defaults to (=${HOME}/.emacs.d=).  This =org-mode= file will tangle their component code-blocks into those files at the root of the repo.

#+name: emacs-initialize-header
#+begin_src emacs-lisp :output silent
  ;;;; Package --- Emacs initialization
  ;;; Commentary:
  ;; Emacs initialization file
  ;;
  ;; As a literate emacs configuration, we leverage org-babel.
  ;; Our goal here is to load a proper subset of org-mode to
  ;; enable the full configuration.

  ;;; Code:
  ;;  -*- lexical-binding: t; -*-

#+end_src

** =early-init.el=
#+property: toc
This file sets the following types of configuration parameters prior to the initialization of the package system and the GUI components.

1. set the garbage collection threshold to 200MBs while loading (and processing) the subsequent configuration files.
2. disable the provided =package.el= functionality so we can leverage =straight.el= instead.
3. disable file-name-handlers temporarily
4. don't load the =site-lisp/init.el= file, if present
5. disable =menu-bar-lines=, =tool-bar-lines=, and =vertical-scroll-bars= in the =default-frame-alist=
6. we will leverage =native-comp= when available, so report on it's availability

#+begin_src emacs-lisp :results none :exports code :noweb yes :tangle ../early-init.el
  <<emacs-initialize-header>>

#+end_src
